bookkeep/urls.py
from django.contrib import admin
from django.urls import path
from calc import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='homePG'),
    path('enter', views.enter, name='formPG'),
    path('enterd', views.enterdebt, name='debtPG'),
    path('records', views.listdisplay, name='recordPG'),
    path('ceet/<int:pk>/', views.ceetdisplay, name='ceetPG'),
]

calc/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Record(models.Model):
    name = models.CharField(max_length=30, unique=True)
    creation_date = models.DateTimeField(default=datetime.now())
    number = models.IntegerField()
    email = models.EmailField()
    address = models.CharField(max_length=100)
    
    def __str__(self):
        return self.email


class History(models.Model):
    name = models.ForeignKey(Record, on_delete=models.CASCADE)
    loan_amount = models.IntegerField()
    percentage = models.IntegerField()


    def interest(self):
        return self.loan_amount * self.percentage / 100

    def time(self):
        return self.loan_amount / self.interest()

    def __str__(self):
        return self.name.name

calc/forms.py
from django import forms
from .models import History, Record

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        exclude = ['creation_date']

    def __init__(self, *args, **kwargs):
        super(RecordForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Enter Client Name'
        self.fields['number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Client Email'
        self.fields['address'].widget.attrs['placeholder'] = 'Enter Client Address'


class HistoryForm(forms.ModelForm):
    class Meta:
        model = History
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(HistoryForm, self).__init__(*args, **kwargs)
        self.fields['loan_amount'].widget.attrs['placeholder'] = 'Enter Loan Amount'
        self.fields['percentage'].widget.attrs['placeholder'] = 'Enter Percent'

calc/views.py
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, ListView, DetailView,
                                    CreateView, UpdateView, DeleteView)
from .forms import RecordForm, HistoryForm
from .models import Record, History

# Create your views here.

def home(request):
    return render(request, 'index.html')


def enter(request):
    if request.method == 'POST':
        form = RecordForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('recordPG')
        else:
            print(form.errors)
    else:
        form = RecordForm()
    context = {
        'form' : form,
    }
    return render(request, 'content/wallet/form.html', context)


def enterdebt(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        entries = History.objects.filter(name=name)
        form = HistoryForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('recordPG')
        else:
            print(form.errors)
    else:
        form = HistoryForm()
    context = {
        'form' : form,
    }
    return render(request, 'content/wallet/form2.html', context)


def listdisplay(request):
    records = Record.objects.all()

    return render(request, 'content/wallet/articles.html', {'records':records})


def ceetdisplay(request, pk):
    record = Record.objects.get(id=pk)
    
    return render(request, 'content/wallet/item.html', {'record':record})

templates/ceet.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <div class="table"></div>
    <table class="table table-striped">
    
       
            <thead>
                <tr>
                    <th>Customer Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    <th>Profile Creation Date&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    <th>Phone Number&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    <th>Email&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    <th>Address&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for i in record.history_set.all %}
                <tr>
                    <td>{{ i.name.name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>{{ i.loan_amount }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>{{ i.paid_amount }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>{{ i.balance }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>{{ record.name.address }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>

                    {% comment %} <td><a href="{% url 'update' pk=object.pk %}">Update</a></td>
                        <td><a href="{% url 'delete' pk=object.pk %}">Delete</a></td> {% endcomment %}
                
                </tr>

                <tr>
                    <th>Loan Amount&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    <th>Paid Amount&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    <th>Balance&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    
                </tr>

                <tr>

                    <td>{{ record.loan_amount }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>{{ record.paid_amount }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>{{ record.balance }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>

                </tr>
                {% endfor %}
            </tbody>

            <h2>Test: </h2>
</body>
</html>

templates/content/wallet/articles.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7 "> <![endif]-->
<!--[if IE 7]><html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]><html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]><html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>

    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title>Bookkeeping App</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'content/wallet/images/favicon.ico' %}">

    <!-- FONTS -->
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,400italic,700'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Patua+One:100,300,400,400italic,700'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,400italic,700,700italic'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Lato:100,300,400'>

    <!-- CSS -->
    <link rel='stylesheet' href="{% static 'css/global.css' %}">
    <link rel='stylesheet' href="{% static 'content/wallet/css/structure.css' %}">
    <link rel='stylesheet' href="{% static 'content/wallet/css/wallet.css' %}">
    <link rel='stylesheet' href="{% static 'content/wallet/css/custom.css' %}>

    <!-- Revolution Slider -->
    <link rel="stylesheet" href="{% static 'plugins/rs-plugin/css/settings.css' %}">

</head>

<body class="color-custom style-simple layout-full-width nice-scroll-on button-flat header-classic minimalist-header-no sticky-header sticky-tb-color ab-show subheader-both-center menu-line-below menuo-right footer-copy-center mobile-tb-left mobile-mini-ml-lc mobile-header-mini tr-menu">
    <div id="Wrapper">
        <div id="Header_wrapper">
            
            <div id="Subheader" style="padding:170px 0 80px;">
                <div class="container">
                    <div class="column one">
                        <h1 class="title">Client Profiles</h1>
                    </div>
                </div>
            </div>
        </div>
        <div id="Content">
            <div class="content_wrapper clearfix">
                <div class="sections_group">

                    
                    <div class="section">
                        <div class="section_wrapper clearfix">
                            <div class="column one column_blog">
                                <div class="blog_wrapper isotope_wrapper">
                                    <div class="posts_group lm_wrapper classic col-3">
                                        {% for object in records %}
                                        <div class="post-item isotope-item clearfix post-2277 post  format-standard has-post-thumbnail  category-events tag-video ">
                                            <div class="date_label">
                                                May 8, 2014
                                            </div>
                                            <div class="image_frame post-photo-wrapper scale-with-grid image">
                                                <div class="image_wrapper">
                                                    <a href="{% url 'ceetPG' pk=object.pk %}">
                                                        <div class="mask"></div><img width="960" height="750" src="{% static 'images/prof1.png' %}" class="scale-with-grid wp-post-image" alt="home_wallet_blog1" />
                                                    </a>
                                                    <div class="image_links double">
                                                        <a href="{% url 'ceetPG' pk=object.pk %}" class="zoom" rel="prettyphoto"><i class="icon-search"></i></a><a href="{% url 'ceetPG' pk=object.pk %}" class="link"><i class="icon-link"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="post-desc-wrapper">
                                                <div class="post-desc">
                                                    <div class="post-head">
                                                        <div class="post-meta clearfix">
                                                            <div class="author-date">
                                                                <span class="vcard author post-author"><span class="label">Created by </span><i class="icon-user"></i> <span class="fn"><a href="#">Admin</a></span></span><span class="date"><span class="label"> at </span><i class="icon-clock"></i> <span class="post-date updated">{{ object.creation_date }}</span></span>
                                                            </div>
                                                            
                                                        </div>
                                                    </div>
                                                    <div class="post-title">
                                                        <h2 class="entry-title" itemprop="headline"><a href="{% url 'ceetPG' pk=object.pk %}">{{object.name}}</a></h2>
                                                    </div>
                                                    <div class="post-excerpt">
                                                        <p>
                                                            Address: {{ object.address }}
                                                            <br>
                                                            Phone Number: {{ object.number }} 
                                                            <br>
                                                            Email: {{ object.email }}
                                                        </p>
                                                    </div>
                                                    <div class="post-footer">
                                                        <div class="button-love">
                                                            <span class="love-text">Number of Entries</span><a href="#" class="mfn-love " data-id="2277"><span class="icons-wrapper"><i class="icon-doc-text"></i><i class="icon-doc-text"></i></span><span class="label">{{ object.history_set.all.count }}</span></a>
                                                        </div>
                                                  
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
    <!-- JS -->
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>

    <script src="{% static 'js/mfn.menu.js' %}"></script>
    <script src="{% static 'js/jquery.plugins.js' %}"></script>
    <script src="{% static 'js/jquery.jplayer.min.js' %}"></script>
    <script src="{% static 'js/animations/animations.js' %}"></script>
    <script src="{% static 'js/translate3d.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

    <script id="mfn-dnmc-retina-js">
        jQuery(window).load(function() {
            var retina = window.devicePixelRatio > 1 ? true : false;
            if (retina) {
                var retinaEl = jQuery("#logo img.logo-main");
                var retinaLogoW = retinaEl.width();
                var retinaLogoH = retinaEl.height();
                retinaEl.attr("src", "images/retina-wallet.png").width(retinaLogoW).height(retinaLogoH);
                var stickyEl = jQuery("#logo img.logo-sticky");
                var stickyLogoW = stickyEl.width();
                var stickyLogoH = stickyEl.height();
                stickyEl.attr("src", "images/retina-wallet.png").width(stickyLogoW).height(stickyLogoH);
                var mobileEl = jQuery("#logo img.logo-mobile");
                var mobileLogoW = mobileEl.width();
                var mobileLogoH = mobileEl.height();
                mobileEl.attr("src", "images/retina-wallet.png").width(mobileLogoW).height(mobileLogoH);
            }
        });
    </script>
</body>

</html>

templates/content/wallet/item.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7 "> <![endif]-->
<!--[if IE 7]><html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]><html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]><html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>

    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title>Bookkeeping App</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'content/wallet/images/favicon.ico' %}">

    <!-- FONTS -->
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,400italic,700'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Patua+One:100,300,400,400italic,700'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,400italic,700,700italic'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Lato:100,300,400'>

    <!-- CSS -->
    <link rel='stylesheet' href="{% static 'css/global.css' %}">
    <link rel='stylesheet' href="{% static 'content/wallet/css/structure.css' %}">
    <link rel='stylesheet' href="{% static 'content/wallet/css/wallet.css' %}">
    <link rel='stylesheet' href="{% static 'content/wallet/css/custom.css' %}>

    <!-- Revolution Slider -->
    <link rel="stylesheet" href="{% static 'plugins/rs-plugin/css/settings.css' %}">

</head>

<body class="color-custom style-simple layout-full-width nice-scroll-on button-flat header-classic minimalist-header-no sticky-header sticky-tb-color ab-show subheader-both-center menu-line-below menuo-right footer-copy-center mobile-tb-left mobile-mini-ml-lc mobile-header-mini tr-menu">
    <div id="Wrapper">
        <div id="Header_wrapper">
            
            <div id="Subheader" style="padding:170px 0 80px;">
                <div class="container">
                    <div class="column one">
                        <h1 class="title">Client Record</h1>
                    </div>
                </div>
            </div>
        </div>
        <div id="Content">
            <div class="content_wrapper clearfix">
                <div class="sections_group">
                    <div id="post-2283" class="no-title no-share post-2283 post  format-standard has-post-thumbnail  category-events tag-design">
                        <div class="section section-post-header">
                            <div class="section_wrapper clearfix">
                                <div class="column one post-nav minimal">
                                    <a class="next" href="{% url 'recordPG' %}"><i class="icon icon-right-open-big"></i></a>
                                    </li>
                                    <a class="home" href="{% url 'homePG' %}"> 
                                        <svg class="icon" width="22" height="22" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M7,2v5H2V2H7 M9,0H0v9h9V0L9,0z" />
                                            <path d="M20,2v5h-5V2H20 M22,0h-9v9h9V0L22,0z" />
                                            <path d="M7,15v5H2v-5H7 M9,13H0v9h9V13L9,13z" />
                                            <path d="M20,15v5h-5v-5H20 M22,13h-9v9h9V13L22,13z" />
                                        </svg>
                                    </a>
                                </div>
                                <div class="column one post-header">
                                    
                                    <div class="title_wrapper">
                                        <div class="post-meta clearfix">
                                            <div class="author-date">
                                                <span class="vcard author post-author"> <span class="label">Created by</span> <i class="icon-user"></i> <span class="fn"><a href="#">Admin</a></span> </span><span class="date"> <span class="label">at</span> <i class="icon-clock"></i>
                                                <time class="entry-date" datetime="2014-05-05T09:34:27+00:00" itemprop="datePublished" pubdate>
                                                    {{ record.creation_date }}
                                                </time>
                                                </span>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                                <div class="column one single-photo-wrapper image">
                                    <div class="image_frame scale-with-grid ">
                                        <div class="image_wrapper">
                                            <a href="images/home_wallet_blog4-1200x800.jpg" rel="prettyphoto">
                                                <div class="mask"></div><img width="1200" height="480" src="{% static 'images/prof1.png' %}" class="scale-with-grid wp-post-image" alt="home_wallet_blog4" />
                                            </a>
                                            <div class="image_links">
                                                <a href="images/home_wallet_blog4-1200x800.jpg" class="zoom" rel="prettyphoto"><i class="icon-search"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="post-wrapper-content">
                            <div class="section mcb-section" style="padding-top:10px; padding-bottom:0px;">
                                <div class="section_wrapper mcb-section-inner">
                                    <div class="wrap mcb-wrap one  valign-top clearfix">
                                        <div class="mcb-wrap-inner">
                                            <div class="column mcb-column one-fifth column_placeholder">
                                                <div class="placeholder">
                                                    &nbsp;
                                                </div>
                                            </div>
                                            <div class="section mcb-section" style="padding-top:90px; padding-bottom:50px; background-color:#3e6edf">
                                                <div class="section_wrapper mcb-section-inner">
                                                    <div class="wrap mcb-wrap one  valign-top clearfix">
                                                        <div class="mcb-wrap-inner" style="display: flex; flex-direction: row; flex-wrap: wrap;">
                                                            <div class="column mcb-column one column_column" style="width: 100%;">
                                                                <div class="column_attr clearfix align_center" style=" padding:0 12%;">
                                                                    <h2 style="color: #fff;">{{ record.name }}</h2>
                                                                    <h6 style="color: #d8e2f9;">This is supposed to be more information about the transactions made.</h6>
                                                                </div>
                                                            </div>
                                                           <div class="column mcb-column three-fifth column_column " style="color: #fff; width: 100%;">
                                                                <div class="column_attr clearfix">
                                                                    <table class="table">
                                                                        <thead class="thead-dark">
                                                                        <tr>
                                                                            <th scope="col">Loan Amount</th>
                                                                            <th scope="col">%</th>
                                                                            <th scope="col">Percentage Share</th>
                                                                            <th scope="col">Duration</th>
                                                                        </tr>
                                                                        </thead>
                                                                        <tbody>
                                                                        {% for i in record.history_set.all %}
                                                                        <tr>
                                                                            <td>{{ i.loan_amount }}</td>
                                                                            <td>{{ i.percentage }}</td>
                                                                            <td>{{ i.interest }}</td>
                                                                            <td>{{ i.time }} Days</td>

                                                                        </tr>
                                                                        {% endfor %}
                                                                        </tbody>
                                                                    </table>
                                                                    
                                                                    
                                                                </div>
                                                            </div> 
                                                        </div>
                                                        
                                                    </div>
                                                </div>
                                            </div>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                                <br>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
    </div>
    
    <!-- JS -->
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>

    <script src="{% static 'js/mfn.menu.js' %}"></script>
    <script src="{% static 'js/jquery.plugins.js' %}"></script>
    <script src="{% static 'js/jquery.jplayer.min.js' %}"></script>
    <script src="{% static 'js/animations/animations.js' %}"></script>
    <script src="{% static 'js/translate3d.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

    <script id="mfn-dnmc-retina-js">
        jQuery(window).load(function() {
            var retina = window.devicePixelRatio > 1 ? true : false;
            if (retina) {
                var retinaEl = jQuery("#logo img.logo-main");
                var retinaLogoW = retinaEl.width();
                var retinaLogoH = retinaEl.height();
                retinaEl.attr("src", "images/retina-wallet.png").width(retinaLogoW).height(retinaLogoH);
                var stickyEl = jQuery("#logo img.logo-sticky");
                var stickyLogoW = stickyEl.width();
                var stickyLogoH = stickyEl.height();
                stickyEl.attr("src", "images/retina-wallet.png").width(stickyLogoW).height(stickyLogoH);
                var mobileEl = jQuery("#logo img.logo-mobile");
                var mobileLogoW = mobileEl.width();
                var mobileLogoH = mobileEl.height();
                mobileEl.attr("src", "images/retina-wallet.png").width(mobileLogoW).height(mobileLogoH);
            }
        });
    </script>
</body>

</html>

templates/form.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Entry Form</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <div>
                <input type="submit" value="Submit">
            </div>
    </form>
</body>
</html>

templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>This is the temporary Homepage!</h1>
</body>
</html>

templates/records.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Records</title>
</head>
<body>
    <div class="table"></div>
<table class="table table-striped">

   
        <thead>
            <tr>
                <th>Customer Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th> Entry date&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>Loan Amount&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                
            </tr>
        </thead>
        <tbody>
            {% for object in records %} 
                <tr>
                    <td><a href="{% url 'deetPG' pk=object.pk %}">{{ object.name.name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></td>


                    {% comment %} <td><a href="{% url 'update' pk=object.pk %}">Update</a></td>
                    <td><a href="{% url 'delete' pk=object.pk %}">Delete</a></td> {% endcomment %}

                    </td>
                
                </tr>
            {% endfor %}
	
		</tbody>
 </table>
</body>
</html>

templates/rectest.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Records</title>
</head>
<body>
    <div class="table"></div>
<table class="table table-striped">

   
        <thead>
            <tr>
                <th>Customer Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th> Entry date&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>Loan Amount&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                
            </tr>
        </thead>
        <tbody>
            {% for object in records %} 
                <tr>
                    <td><a href="{% url 'ceetPG' pk=object.pk %}">{{ object.name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></td>


                    {% comment %} <td><a href="{% url 'update' pk=object.pk %}">Update</a></td>
                    <td><a href="{% url 'delete' pk=object.pk %}">Delete</a></td> {% endcomment %}

                    </td>
                
                </tr>
            {% endfor %}
	
		</tbody>
 </table>
</body>
</html>